development:
  adapter: postgresql
  encoding: utf8
  database: naawayday_feed_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: naawayday_feed_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: naawayday_feed_production
  pool: 5
  username:
  password: